import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from dotenv import load_dotenv

load_dotenv()


EMAIL_ADDRESS = os.getenv("EMAIL_ADDRESS")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
EMAIL_FROM_NAME = os.getenv("EMAIL_FROM_NAME", "CareLink AI")
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")


def _build_template(title: str, heading: str, body: str) -> str:

    return f"""
<!DOCTYPE html>
<html>

<head>

<meta charset="UTF-8">

<meta
    name="viewport"
    content="width=device-width, initial-scale=1.0"
/>

<title>{title}</title>

<style>

*{{
    margin:0;
    padding:0;
    box-sizing:border-box;
}}

body{{
    background:#eef3f8;
    font-family:Arial,Helvetica,sans-serif;
    padding:30px;
}}

.wrapper{{
    max-width:700px;
    margin:auto;
}}

.card{{
    background:#ffffff;
    border-radius:18px;
    overflow:hidden;
    box-shadow:0 10px 35px rgba(0,0,0,.12);
}}

.header{{
    background:linear-gradient(
        135deg,
        #1565C0,
        #0D47A1
    );
    padding:40px;
    text-align:center;
    color:white;
}}

.logo{{
    width:72px;
    height:72px;
    border-radius:50%;
    background:white;
    color:#1565C0;
    font-size:34px;
    font-weight:bold;
    display:inline-flex;
    align-items:center;
    justify-content:center;
    margin-bottom:18px;
}}

.header h1{{
    font-size:34px;
    margin-bottom:8px;
}}

.header p{{
    opacity:.95;
    font-size:15px;
}}

.content{{
    padding:40px;
    color:#2d3748;
    line-height:1.8;
}}

.badge{{
    display:inline-block;
    padding:8px 16px;
    background:#E3F2FD;
    color:#1565C0;
    font-weight:bold;
    border-radius:30px;
    margin-bottom:25px;
}}

.heading{{
    font-size:28px;
    margin-bottom:20px;
    color:#0D47A1;
}}

.info-box{{
    background:#f8fbff;
    border-left:5px solid #1565C0;
    padding:20px;
    border-radius:10px;
    margin:25px 0;
}}

.button-container{{
    text-align:center;
    margin:40px 0;
}}

.button{{
    display:inline-block;
    background:#1565C0;
    color:white !important;
    text-decoration:none;
    padding:15px 34px;
    border-radius:10px;
    font-size:16px;
    font-weight:bold;
}}

.button:hover{{
    background:#0D47A1;
}}

.footer{{
    background:#f5f7fb;
    text-align:center;
    padding:30px;
    color:#6b7280;
    font-size:13px;
}}

.footer hr{{
    border:none;
    border-top:1px solid #dbe3ec;
    margin-bottom:18px;
}}

.footer strong{{
    color:#1565C0;
}}

@media only screen and (max-width:600px){{

.content{{
padding:25px;
}}

.header{{
padding:28px;
}}

.heading{{
font-size:22px;
}}

.button{{
display:block;
}}

}}

</style>

</head>

<body>

<div class="wrapper">

<div class="card">

<div class="header">

<div class="logo">
💙
</div>

<h1>CareLink AI</h1>

<p>
Smart Donations • Greater Impact
</p>

</div>

<div class="content">

<div class="badge">
AUTOMATED NOTIFICATION
</div>

<h2 class="heading">
{heading}
</h2>

<div class="info-box">

{body}

</div>

<div class="button-container">

<a
class="button"
href="{FRONTEND_URL}"
>

Open CareLink AI

</a>

</div>
</div>

<div class="footer">

<hr>

<p>
This is an automated email generated by
<strong>CareLink AI</strong>.
</p>

<p style="margin-top:8px;">
Please do not reply to this email.
</p>

<p style="margin-top:18px;">
© 2026 CareLink AI • Smart Donations • Greater Impact
</p>

</div>

</div>

</div>

</body>

</html>
"""


def send_email(
    recipient: str,
    subject: str,
    heading: str,
    body: str,
):

    if not EMAIL_ADDRESS or not EMAIL_PASSWORD:
        print("Email credentials not configured.")
        return False

    try:

        message = MIMEMultipart("alternative")

        message["Subject"] = subject
        message["From"] = f"{EMAIL_FROM_NAME} <{EMAIL_ADDRESS}>"
        message["To"] = recipient

        html = _build_template(
            title=subject,
            heading=heading,
            body=body,
        )

        message.attach(
            MIMEText(
                html,
                "html",
                "utf-8",
            )
        )

        with smtplib.SMTP(
            "smtp.gmail.com",
            587,
        ) as server:

            server.ehlo()

            server.starttls()

            server.ehlo()

            server.login(
                EMAIL_ADDRESS,
                EMAIL_PASSWORD,
            )

            server.sendmail(
                EMAIL_ADDRESS,
                recipient,
                message.as_string(),
            )

        print(
            f"✅ Email sent successfully to {recipient}"
        )

        return True

    except Exception as e:

        print(
            f"❌ EMAIL ERROR: {e}"
        )

        return False