"""add_donation_location

Revision ID: 3c5779548010
Revises: create_matches_notifications
Create Date: 2026-07-16 12:08:36.547585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c5779548010'
down_revision: Union[str, Sequence[str], None] = 'create_matches_notifications'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('donations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('donations', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:

    op.drop_column(
        "donations",
        "longitude",
    )

    op.drop_column(
        "donations",
        "latitude",
    )